## DBサーバーのホスト名、指定しなければlocalhost

DBhost: ${DBHOST}
DBport: ${DBPORT}

# データベース名
DBname: ${DBNAME}

# ログイン名とパスワードは環境変数で渡す
DBuser: ${DBUSER}
DBpswd: ${DBPSWD}

# SSH接続を使わない
UseSSH: false

# 既存のトンネルを利用してSSH接続を使う
#UseSSH: false
#DBport: 

# SSH接続を使う
#UseSSH: true
#SSHhost: ${SSHHOST}
#SSHport: ${SSHPORT}
#SSHuser: ${SSHUSER}
##SSHprvkey: ${SSHKEY}
##SSHpswd: ${SSHPSWD}
